"""add scoring_configs

Revision ID: 06071a6cba37
Revises: 0679fca62714
Create Date: 2026-06-29 14:19:18.943823
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '06071a6cba37'
down_revision: Union[str, None] = '0679fca62714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_configs',
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('base_weights', sa.JSON(), nullable=False),
    sa.Column('caps', sa.JSON(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_scoring_configs_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_configs'))
    )
    op.create_index(op.f('ix_scoring_configs_active'), 'scoring_configs', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoring_configs_active'), table_name='scoring_configs')
    op.drop_table('scoring_configs')
    # ### end Alembic commands ###
