"""initial schema

Revision ID: 0679fca62714
Revises: 
Create Date: 2026-06-29 13:52:04.588450
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0679fca62714'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Enum('login', 'login_failed', 'logout', 'token_refresh', 'user_created', 'role_changed', 'company_created', 'company_status_changed', 'deal_type_changed', 'document_uploaded', 'document_status_changed', 'score_computed', 'teaser_published', 'interaction_created', 'interaction_status_changed', 'kyc_check_created', 'kyc_status_changed', 'kyc_hit_alert', 'dataroom_access_granted', 'dataroom_access_revoked', 'dataroom_document_viewed', 'deal_created', 'deal_stage_changed', 'mandate_created', 'mandate_status_changed', 'fee_added', 'mission_reviewed', 'mission_promoted', 'program_created', 'program_member_added', 'dd_computed', 'export', name='auditaction', native_enum=False), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=True),
    sa.Column('object_id', sa.String(length=36), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_object_id'), 'audit_logs', ['object_id'], unique=False)
    op.create_table('deal_types',
    sa.Column('code', sa.Enum('ouverture_capital', 'dette_bancaire', 'dette_privee', 'cession_parts', 'ma', 'hybride', 'partenariat', 'indecis', name='dealtypecode', native_enum=False), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instruments', sa.JSON(), nullable=False),
    sa.Column('target_financiers', sa.Text(), nullable=True),
    sa.Column('doc_checklist', sa.JSON(), nullable=False),
    sa.Column('questionnaire_branch', sa.JSON(), nullable=False),
    sa.Column('teaser_template', sa.String(length=120), nullable=True),
    sa.Column('scoring_weights', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_types')),
    sa.UniqueConstraint('code', name=op.f('uq_deal_types_code'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('entrepreneur', 'investisseur', 'analyste', 'senior', 'conformite', 'sponsor', 'admin', name='role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.Enum('BJ', 'BF', 'CI', 'GW', 'ML', 'NE', 'SN', 'TG', 'CM', 'CF', 'CG', 'GA', 'GQ', 'TD', name='country', native_enum=False), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=False),
    sa.Column('rccm', sa.String(length=120), nullable=True),
    sa.Column('stage', sa.Enum('idee', 'amorcage', 'early', 'croissance', 'mature', name='companystage', native_enum=False), nullable=True),
    sa.Column('status', sa.Enum('brouillon', 'qualifie', 'en_preparation', 'investor_ready', 'en_deal', 'clos', 'archive', name='companystatus', native_enum=False), nullable=False),
    sa.Column('revenue_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('revenue_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('XOF', 'XAF', 'EUR', 'USD', name='currency', native_enum=False), nullable=False),
    sa.Column('financials_reliability', sa.Enum('declare_non_audite', 'verifie', 'ia_a_verifier', 'inference', name='datareliability', native_enum=False), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_companies_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_owner_id'), 'companies', ['owner_id'], unique=False)
    op.create_index(op.f('ix_companies_rccm'), 'companies', ['rccm'], unique=False)
    op.create_table('investors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('equity_pe_vc', 'dette_mezzanine', 'dfi', 'family_office', 'corporate', 'banque', name='investortype', native_enum=False), nullable=False),
    sa.Column('jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('qualif_status', sa.Enum('prospect', 'qualifie', 'actif', 'inactif', name='investorqualifstatus', native_enum=False), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_investors_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investors'))
    )
    op.create_index(op.f('ix_investors_name'), 'investors', ['name'], unique=False)
    op.create_index(op.f('ix_investors_user_id'), 'investors', ['user_id'], unique=False)
    op.create_table('kyc_checks',
    sa.Column('subject_type', sa.Enum('company', 'investor', name='kycsubjecttype', native_enum=False), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('subject_label', sa.String(length=255), nullable=True),
    sa.Column('check_type', sa.Enum('kyb', 'aml_screening', 'manuelle', name='kycchecktype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('en_attente', 'valide', 'rejete', 'hit', name='kycstatus', native_enum=False), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checked_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['checked_by'], ['users.id'], name=op.f('fk_kyc_checks_checked_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_checks'))
    )
    op.create_index(op.f('ix_kyc_checks_subject_id'), 'kyc_checks', ['subject_id'], unique=False)
    op.create_table('programs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sponsor_name', sa.String(length=255), nullable=False),
    sa.Column('sponsor_user_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('deliverables', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('actif', 'clos', name='programstatus', native_enum=False), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_programs_created_by_users')),
    sa.ForeignKeyConstraint(['sponsor_user_id'], ['users.id'], name=op.f('fk_programs_sponsor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs'))
    )
    op.create_index(op.f('ix_programs_sponsor_user_id'), 'programs', ['sponsor_user_id'], unique=False)
    op.create_table('contacts',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('kyc_done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_contacts_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_table('datarooms',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('ouverte', 'fermee', name='dataroomstatus', native_enum=False), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_datarooms_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_datarooms_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datarooms'))
    )
    op.create_index(op.f('ix_datarooms_company_id'), 'datarooms', ['company_id'], unique=True)
    op.create_table('deal_type_history',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('old_primary', sa.Enum('ouverture_capital', 'dette_bancaire', 'dette_privee', 'cession_parts', 'ma', 'hybride', 'partenariat', 'indecis', name='dealtypecode', native_enum=False), nullable=True),
    sa.Column('new_primary', sa.Enum('ouverture_capital', 'dette_bancaire', 'dette_privee', 'cession_parts', 'ma', 'hybride', 'partenariat', 'indecis', name='dealtypecode', native_enum=False), nullable=True),
    sa.Column('old_secondary', sa.Enum('ouverture_capital', 'dette_bancaire', 'dette_privee', 'cession_parts', 'ma', 'hybride', 'partenariat', 'indecis', name='dealtypecode', native_enum=False), nullable=True),
    sa.Column('new_secondary', sa.Enum('ouverture_capital', 'dette_bancaire', 'dette_privee', 'cession_parts', 'ma', 'hybride', 'partenariat', 'indecis', name='dealtypecode', native_enum=False), nullable=True),
    sa.Column('source', sa.Enum('entrepreneur', 'cabinet', name='dealtypechangesource', native_enum=False), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_deal_type_history_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_type_history'))
    )
    op.create_index(op.f('ix_deal_type_history_company_id'), 'deal_type_history', ['company_id'], unique=False)
    op.create_table('documents',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=120), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('recu', 'verifie', 'rejete', name='documentstatus', native_enum=False), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_documents_company_id_companies')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_table('esg_profiles',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('jobs_total', sa.Integer(), nullable=True),
    sa.Column('jobs_female', sa.Integer(), nullable=True),
    sa.Column('jobs_youth', sa.Integer(), nullable=True),
    sa.Column('women_in_leadership', sa.Boolean(), nullable=True),
    sa.Column('environmental_policy', sa.Boolean(), nullable=True),
    sa.Column('climate_risk_assessed', sa.Boolean(), nullable=True),
    sa.Column('governance_formalized', sa.Boolean(), nullable=True),
    sa.Column('board_independent', sa.Boolean(), nullable=True),
    sa.Column('esg_required', sa.Boolean(), nullable=False),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_esg_profiles_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_esg_profiles'))
    )
    op.create_index(op.f('ix_esg_profiles_company_id'), 'esg_profiles', ['company_id'], unique=True)
    op.create_table('financing_needs',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('XOF', 'XAF', 'EUR', 'USD', name='currency', native_enum=False), nullable=False),
    sa.Column('use_of_funds', sa.Text(), nullable=True),
    sa.Column('horizon', sa.String(length=120), nullable=True),
    sa.Column('deal_type_primary', sa.Enum('ouverture_capital', 'dette_bancaire', 'dette_privee', 'cession_parts', 'ma', 'hybride', 'partenariat', 'indecis', name='dealtypecode', native_enum=False), nullable=True),
    sa.Column('deal_type_secondary', sa.Enum('ouverture_capital', 'dette_bancaire', 'dette_privee', 'cession_parts', 'ma', 'hybride', 'partenariat', 'indecis', name='dealtypecode', native_enum=False), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_financing_needs_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financing_needs'))
    )
    op.create_index(op.f('ix_financing_needs_company_id'), 'financing_needs', ['company_id'], unique=True)
    op.create_table('investment_criteria',
    sa.Column('investor_id', sa.String(length=36), nullable=False),
    sa.Column('countries', sa.JSON(), nullable=False),
    sa.Column('sectors', sa.JSON(), nullable=False),
    sa.Column('instruments', sa.JSON(), nullable=False),
    sa.Column('deal_types', sa.JSON(), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('exclusions', sa.JSON(), nullable=False),
    sa.Column('ticket_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ticket_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ticket_currency', sa.Enum('XOF', 'XAF', 'EUR', 'USD', name='currency', native_enum=False), nullable=False),
    sa.Column('esg_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], name=op.f('fk_investment_criteria_investor_id_investors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investment_criteria'))
    )
    op.create_index(op.f('ix_investment_criteria_investor_id'), 'investment_criteria', ['investor_id'], unique=True)
    op.create_table('missions',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('en_cours', 'livre', name='missionstatus', native_enum=False), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_missions_company_id_companies')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_missions_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_missions'))
    )
    op.create_index(op.f('ix_missions_company_id'), 'missions', ['company_id'], unique=True)
    op.create_table('onboarding_sessions',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_text', sa.Text(), nullable=True),
    sa.Column('gating_route', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_onboarding_sessions_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_sessions'))
    )
    op.create_index(op.f('ix_onboarding_sessions_company_id'), 'onboarding_sessions', ['company_id'], unique=True)
    op.create_table('program_members',
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_program_members_company_id_companies')),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_program_members_program_id_programs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_members'))
    )
    op.create_index(op.f('ix_program_members_company_id'), 'program_members', ['company_id'], unique=False)
    op.create_index(op.f('ix_program_members_program_id'), 'program_members', ['program_id'], unique=False)
    op.create_table('quote_requests',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('offer_key', sa.String(length=60), nullable=True),
    sa.Column('deal_type', sa.Enum('ouverture_capital', 'dette_bancaire', 'dette_privee', 'cession_parts', 'ma', 'hybride', 'partenariat', 'indecis', name='dealtypecode', native_enum=False), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_quote_requests_company_id_companies')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_quote_requests_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_requests'))
    )
    op.create_index(op.f('ix_quote_requests_company_id'), 'quote_requests', ['company_id'], unique=False)
    op.create_table('scores',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('subscores', sa.JSON(), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('category', sa.Enum('investor_ready', 'a_preparer', 'plutot_dette_banque', 'trop_precoce', name='readinesscategory', native_enum=False), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('grid_version', sa.String(length=40), nullable=True),
    sa.Column('deal_type_applied', sa.Enum('ouverture_capital', 'dette_bancaire', 'dette_privee', 'cession_parts', 'ma', 'hybride', 'partenariat', 'indecis', name='dealtypecode', native_enum=False), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_scores_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores'))
    )
    op.create_index(op.f('ix_scores_company_id'), 'scores', ['company_id'], unique=True)
    op.create_table('syscohada_imports',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('fiscal_year', sa.String(length=12), nullable=True),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('imported_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_syscohada_imports_company_id_companies')),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], name=op.f('fk_syscohada_imports_imported_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_syscohada_imports'))
    )
    op.create_index(op.f('ix_syscohada_imports_company_id'), 'syscohada_imports', ['company_id'], unique=False)
    op.create_table('teasers',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('deal_type', sa.Enum('ouverture_capital', 'dette_bancaire', 'dette_privee', 'cession_parts', 'ma', 'hybride', 'partenariat', 'indecis', name='dealtypecode', native_enum=False), nullable=True),
    sa.Column('template', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=False),
    sa.Column('zone', sa.String(length=40), nullable=True),
    sa.Column('revenue_band', sa.String(length=60), nullable=True),
    sa.Column('amount_band', sa.String(length=60), nullable=True),
    sa.Column('instrument', sa.Enum('equity', 'dette', 'quasi_equity', 'subvention', 'hybride', 'variable', name='instrument', native_enum=False), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('brouillon', 'publie', 'retire', name='teaserstatus', native_enum=False), nullable=False),
    sa.Column('validated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_teasers_company_id_companies')),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], name=op.f('fk_teasers_validated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teasers'))
    )
    op.create_index(op.f('ix_teasers_company_id'), 'teasers', ['company_id'], unique=True)
    op.create_table('dataroom_access',
    sa.Column('dataroom_id', sa.String(length=36), nullable=False),
    sa.Column('investor_id', sa.String(length=36), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataroom_id'], ['datarooms.id'], name=op.f('fk_dataroom_access_dataroom_id_datarooms')),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_dataroom_access_granted_by_users')),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], name=op.f('fk_dataroom_access_investor_id_investors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataroom_access'))
    )
    op.create_index(op.f('ix_dataroom_access_dataroom_id'), 'dataroom_access', ['dataroom_id'], unique=False)
    op.create_index(op.f('ix_dataroom_access_investor_id'), 'dataroom_access', ['investor_id'], unique=False)
    op.create_table('dataroom_documents',
    sa.Column('dataroom_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataroom_id'], ['datarooms.id'], name=op.f('fk_dataroom_documents_dataroom_id_datarooms')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_dataroom_documents_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataroom_documents'))
    )
    op.create_index(op.f('ix_dataroom_documents_dataroom_id'), 'dataroom_documents', ['dataroom_id'], unique=False)
    op.create_table('dataroom_logs',
    sa.Column('dataroom_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('investor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.Enum('consultation', 'telechargement', name='dataroomlogaction', native_enum=False), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataroom_id'], ['datarooms.id'], name=op.f('fk_dataroom_logs_dataroom_id_datarooms')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_dataroom_logs_document_id_documents')),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], name=op.f('fk_dataroom_logs_investor_id_investors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataroom_logs'))
    )
    op.create_index(op.f('ix_dataroom_logs_dataroom_id'), 'dataroom_logs', ['dataroom_id'], unique=False)
    op.create_table('dd_analyses',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=True),
    sa.Column('deal_type', sa.Enum('ouverture_capital', 'dette_bancaire', 'dette_privee', 'cession_parts', 'ma', 'hybride', 'partenariat', 'indecis', name='dealtypecode', native_enum=False), nullable=True),
    sa.Column('class_totals', sa.JSON(), nullable=False),
    sa.Column('retraitements', sa.JSON(), nullable=False),
    sa.Column('focus', sa.JSON(), nullable=False),
    sa.Column('synthesis', sa.Text(), nullable=True),
    sa.Column('grid_version', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_dd_analyses_company_id_companies')),
    sa.ForeignKeyConstraint(['import_id'], ['syscohada_imports.id'], name=op.f('fk_dd_analyses_import_id_syscohada_imports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dd_analyses'))
    )
    op.create_index(op.f('ix_dd_analyses_company_id'), 'dd_analyses', ['company_id'], unique=False)
    op.create_table('deliverables',
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('business_plan', 'modele_financier', 'valorisation', 'teaser', 'data_room_init', name='deliverablekind', native_enum=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('brouillon', 'soumis', 'valide', name='deliverablestatus', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name=op.f('fk_deliverables_mission_id_missions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliverables'))
    )
    op.create_index(op.f('ix_deliverables_mission_id'), 'deliverables', ['mission_id'], unique=False)
    op.create_table('interactions',
    sa.Column('teaser_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('investor_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('interesse', 'ecarte', 'nda_envoye', 'nda_signe', name='interactionstatus', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_interactions_company_id_companies')),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], name=op.f('fk_interactions_investor_id_investors')),
    sa.ForeignKeyConstraint(['teaser_id'], ['teasers.id'], name=op.f('fk_interactions_teaser_id_teasers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactions'))
    )
    op.create_index(op.f('ix_interactions_company_id'), 'interactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_interactions_investor_id'), 'interactions', ['investor_id'], unique=False)
    op.create_index(op.f('ix_interactions_teaser_id'), 'interactions', ['teaser_id'], unique=False)
    op.create_table('mission_reviews',
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('entrepreneur', 'investisseur', 'analyste', 'senior', 'conformite', 'sponsor', 'admin', name='role', native_enum=False), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name=op.f('fk_mission_reviews_mission_id_missions')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_mission_reviews_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_reviews'))
    )
    op.create_index(op.f('ix_mission_reviews_mission_id'), 'mission_reviews', ['mission_id'], unique=False)
    op.create_table('mission_tasks',
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name=op.f('fk_mission_tasks_mission_id_missions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_tasks'))
    )
    op.create_index(op.f('ix_mission_tasks_mission_id'), 'mission_tasks', ['mission_id'], unique=False)
    op.create_table('deals',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('investor_id', sa.String(length=36), nullable=False),
    sa.Column('interaction_id', sa.String(length=36), nullable=True),
    sa.Column('deal_type', sa.Enum('ouverture_capital', 'dette_bancaire', 'dette_privee', 'cession_parts', 'ma', 'hybride', 'partenariat', 'indecis', name='dealtypecode', native_enum=False), nullable=True),
    sa.Column('stage', sa.Enum('interesse', 'nda', 'data_room', 'due_diligence', 'term_sheet', 'closing', 'abandonne', name='dealstage', native_enum=False), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_deals_company_id_companies')),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name=op.f('fk_deals_interaction_id_interactions')),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], name=op.f('fk_deals_investor_id_investors')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_deals_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals'))
    )
    op.create_index(op.f('ix_deals_company_id'), 'deals', ['company_id'], unique=False)
    op.create_index(op.f('ix_deals_investor_id'), 'deals', ['investor_id'], unique=False)
    op.create_table('qa_items',
    sa.Column('interaction_id', sa.String(length=36), nullable=False),
    sa.Column('asked_by', sa.String(length=36), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('ouverte', 'repondue', 'cloturee', name='qastatus', native_enum=False), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], name=op.f('fk_qa_items_answered_by_users')),
    sa.ForeignKeyConstraint(['asked_by'], ['users.id'], name=op.f('fk_qa_items_asked_by_users')),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name=op.f('fk_qa_items_interaction_id_interactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_items'))
    )
    op.create_index(op.f('ix_qa_items_interaction_id'), 'qa_items', ['interaction_id'], unique=False)
    op.create_table('deal_milestones',
    sa.Column('deal_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_deal_milestones_deal_id_deals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_milestones'))
    )
    op.create_index(op.f('ix_deal_milestones_deal_id'), 'deal_milestones', ['deal_id'], unique=False)
    op.create_table('deal_stage_history',
    sa.Column('deal_id', sa.String(length=36), nullable=False),
    sa.Column('old_stage', sa.Enum('interesse', 'nda', 'data_room', 'due_diligence', 'term_sheet', 'closing', 'abandonne', name='dealstage', native_enum=False), nullable=True),
    sa.Column('new_stage', sa.Enum('interesse', 'nda', 'data_room', 'due_diligence', 'term_sheet', 'closing', 'abandonne', name='dealstage', native_enum=False), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_deal_stage_history_deal_id_deals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_stage_history'))
    )
    op.create_index(op.f('ix_deal_stage_history_deal_id'), 'deal_stage_history', ['deal_id'], unique=False)
    op.create_table('mandates',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('deal_id', sa.String(length=36), nullable=True),
    sa.Column('represented_party', sa.Enum('entreprise', 'investisseur', 'les_deux', name='representedparty', native_enum=False), nullable=False),
    sa.Column('mandate_type', sa.Enum('levee', 'cession', 'sourcing', 'arrangement_dette', 'conseil', 'autre', name='mandatetype', native_enum=False), nullable=False),
    sa.Column('exclusive', sa.Boolean(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('brouillon', 'actif', 'clos', name='mandatestatus', native_enum=False), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_mandates_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_mandates_created_by_users')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_mandates_deal_id_deals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mandates'))
    )
    op.create_index(op.f('ix_mandates_company_id'), 'mandates', ['company_id'], unique=False)
    op.create_index(op.f('ix_mandates_deal_id'), 'mandates', ['deal_id'], unique=False)
    op.create_table('fees',
    sa.Column('mandate_id', sa.String(length=36), nullable=False),
    sa.Column('fee_type', sa.Enum('retainer', 'success_fee', 'arrangement', name='feetype', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('XOF', 'XAF', 'EUR', 'USD', name='currency', native_enum=False), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('du', 'facture', 'paye', name='feestatus', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], name=op.f('fk_fees_mandate_id_mandates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fees'))
    )
    op.create_index(op.f('ix_fees_mandate_id'), 'fees', ['mandate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fees_mandate_id'), table_name='fees')
    op.drop_table('fees')
    op.drop_index(op.f('ix_mandates_deal_id'), table_name='mandates')
    op.drop_index(op.f('ix_mandates_company_id'), table_name='mandates')
    op.drop_table('mandates')
    op.drop_index(op.f('ix_deal_stage_history_deal_id'), table_name='deal_stage_history')
    op.drop_table('deal_stage_history')
    op.drop_index(op.f('ix_deal_milestones_deal_id'), table_name='deal_milestones')
    op.drop_table('deal_milestones')
    op.drop_index(op.f('ix_qa_items_interaction_id'), table_name='qa_items')
    op.drop_table('qa_items')
    op.drop_index(op.f('ix_deals_investor_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_company_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_mission_tasks_mission_id'), table_name='mission_tasks')
    op.drop_table('mission_tasks')
    op.drop_index(op.f('ix_mission_reviews_mission_id'), table_name='mission_reviews')
    op.drop_table('mission_reviews')
    op.drop_index(op.f('ix_interactions_teaser_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_investor_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_company_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_deliverables_mission_id'), table_name='deliverables')
    op.drop_table('deliverables')
    op.drop_index(op.f('ix_dd_analyses_company_id'), table_name='dd_analyses')
    op.drop_table('dd_analyses')
    op.drop_index(op.f('ix_dataroom_logs_dataroom_id'), table_name='dataroom_logs')
    op.drop_table('dataroom_logs')
    op.drop_index(op.f('ix_dataroom_documents_dataroom_id'), table_name='dataroom_documents')
    op.drop_table('dataroom_documents')
    op.drop_index(op.f('ix_dataroom_access_investor_id'), table_name='dataroom_access')
    op.drop_index(op.f('ix_dataroom_access_dataroom_id'), table_name='dataroom_access')
    op.drop_table('dataroom_access')
    op.drop_index(op.f('ix_teasers_company_id'), table_name='teasers')
    op.drop_table('teasers')
    op.drop_index(op.f('ix_syscohada_imports_company_id'), table_name='syscohada_imports')
    op.drop_table('syscohada_imports')
    op.drop_index(op.f('ix_scores_company_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_quote_requests_company_id'), table_name='quote_requests')
    op.drop_table('quote_requests')
    op.drop_index(op.f('ix_program_members_program_id'), table_name='program_members')
    op.drop_index(op.f('ix_program_members_company_id'), table_name='program_members')
    op.drop_table('program_members')
    op.drop_index(op.f('ix_onboarding_sessions_company_id'), table_name='onboarding_sessions')
    op.drop_table('onboarding_sessions')
    op.drop_index(op.f('ix_missions_company_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_investment_criteria_investor_id'), table_name='investment_criteria')
    op.drop_table('investment_criteria')
    op.drop_index(op.f('ix_financing_needs_company_id'), table_name='financing_needs')
    op.drop_table('financing_needs')
    op.drop_index(op.f('ix_esg_profiles_company_id'), table_name='esg_profiles')
    op.drop_table('esg_profiles')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_deal_type_history_company_id'), table_name='deal_type_history')
    op.drop_table('deal_type_history')
    op.drop_index(op.f('ix_datarooms_company_id'), table_name='datarooms')
    op.drop_table('datarooms')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_programs_sponsor_user_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_kyc_checks_subject_id'), table_name='kyc_checks')
    op.drop_table('kyc_checks')
    op.drop_index(op.f('ix_investors_user_id'), table_name='investors')
    op.drop_index(op.f('ix_investors_name'), table_name='investors')
    op.drop_table('investors')
    op.drop_index(op.f('ix_companies_rccm'), table_name='companies')
    op.drop_index(op.f('ix_companies_owner_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('deal_types')
    op.drop_index(op.f('ix_audit_logs_object_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
