"""phase 2 - deal activity signal columns

Revision ID: 37bdcbdd4f47
Revises: 38258af64911
Create Date: 2026-06-26 13:23:34.723050
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bdcbdd4f47'
down_revision: str | None = '38258af64911'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('last_activity_network', sa.String(length=30), nullable=True))
    op.add_column('deals', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'last_activity_at')
    op.drop_column('deals', 'last_activity_network')
    # ### end Alembic commands ###
