"""module 1 - deals, socials, notes, history, enrichment

Revision ID: 38258af64911
Revises: 7331b10b5633
Create Date: 2026-06-26 12:39:07.991446
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38258af64911'
down_revision: str | None = '7331b10b5633'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('founders', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=280), nullable=True),
    sa.Column('deal_source', sa.String(length=20), nullable=True),
    sa.Column('deal_source_other', sa.String(length=120), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('deck_status', sa.String(length=20), nullable=True),
    sa.Column('what_i_know', sa.String(length=500), nullable=True),
    sa.Column('completeness_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals'))
    )
    op.create_table('deal_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_deal_change_logs_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_change_logs'))
    )
    op.create_index(op.f('ix_deal_change_logs_deal_id'), 'deal_change_logs', ['deal_id'], unique=False)
    op.create_table('deal_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_deal_notes_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_notes'))
    )
    op.create_index(op.f('ix_deal_notes_deal_id'), 'deal_notes', ['deal_id'], unique=False)
    op.create_table('enrichment_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_enrichment_runs_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrichment_runs'))
    )
    op.create_index(op.f('ix_enrichment_runs_deal_id'), 'enrichment_runs', ['deal_id'], unique=False)
    op.create_table('social_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('network', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_social_profiles_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_profiles'))
    )
    op.create_index(op.f('ix_social_profiles_deal_id'), 'social_profiles', ['deal_id'], unique=False)
    op.create_table('enrichment_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('suggested_value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('collected_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_enrichment_proposals_deal_id_deals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['enrichment_runs.id'], name=op.f('fk_enrichment_proposals_run_id_enrichment_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrichment_proposals'))
    )
    op.create_index(op.f('ix_enrichment_proposals_deal_id'), 'enrichment_proposals', ['deal_id'], unique=False)
    op.create_index(op.f('ix_enrichment_proposals_run_id'), 'enrichment_proposals', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrichment_proposals_run_id'), table_name='enrichment_proposals')
    op.drop_index(op.f('ix_enrichment_proposals_deal_id'), table_name='enrichment_proposals')
    op.drop_table('enrichment_proposals')
    op.drop_index(op.f('ix_social_profiles_deal_id'), table_name='social_profiles')
    op.drop_table('social_profiles')
    op.drop_index(op.f('ix_enrichment_runs_deal_id'), table_name='enrichment_runs')
    op.drop_table('enrichment_runs')
    op.drop_index(op.f('ix_deal_notes_deal_id'), table_name='deal_notes')
    op.drop_table('deal_notes')
    op.drop_index(op.f('ix_deal_change_logs_deal_id'), table_name='deal_change_logs')
    op.drop_table('deal_change_logs')
    op.drop_table('deals')
    # ### end Alembic commands ###
