"""initial schema - users + reference CI-UEMOA

Revision ID: 7331b10b5633
Revises: 
Create Date: 2026-06-26 12:29:33.998487
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7331b10b5633'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_accelerators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_accelerators')),
    sa.UniqueConstraint('name', name=op.f('uq_ref_accelerators_name'))
    )
    op.create_table('ref_countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_uemoa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_countries')),
    sa.UniqueConstraint('iso2', name=op.f('uq_ref_countries_iso2'))
    )
    op.create_table('ref_deal_source_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_deal_source_types')),
    sa.UniqueConstraint('code', name=op.f('uq_ref_deal_source_types_code'))
    )
    op.create_table('ref_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_funds')),
    sa.UniqueConstraint('name', name=op.f('uq_ref_funds_name'))
    )
    op.create_table('ref_sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_sectors')),
    sa.UniqueConstraint('name', name=op.f('uq_ref_sectors_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ref_sectors')
    op.drop_table('ref_funds')
    op.drop_table('ref_deal_source_types')
    op.drop_table('ref_countries')
    op.drop_table('ref_accelerators')
    # ### end Alembic commands ###
